In [ ]:
import pandas as pd
import numpy as np

# Tải dữ liệu xét tuyển đại học

In [ ]:
df = pd.read_csv('dulieuxettuyendaihoc.csv', index_col="STT")
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

from matplotlib import pyplot as plt
_df_0['T1'].plot(kind='hist', bins=20, title='T1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['L1'].plot(kind='hist', bins=20, title='L1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['H1'].plot(kind='hist', bins=20, title='H1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['S1'].plot(kind='hist', bins=20, title='S1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('GT').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('KV').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('KT').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='T1', y='L1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='L1', y='H1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9.plot(kind='scatter', x='H1', y='S1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_10.plot(kind='scatter', x='S1', y='V1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['DT']
  ys = series['T1']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('DT', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('GT')):
  _plot_series(series, series_name, i)
  fig.legend(title='GT', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('DT')
_ = plt.ylabel('T1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['DT']
  ys = series['T1']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('DT', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('KV')):
  _plot_series(series, series_name, i)
  fig.legend(title='KV', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('DT')
_ = plt.ylabel('T1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['DT']
  ys = series['T1']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('DT', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('KT')):
  _plot_series(series, series_name, i)
  fig.legend(title='KT', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('DT')
_ = plt.ylabel('T1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['DT']
  ys = series['L1']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_14.sort_values('DT', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('GT')):
  _plot_series(series, series_name, i)
  fig.legend(title='GT', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('DT')
_ = plt.ylabel('L1')

from matplotlib import pyplot as plt
_df_15['T1'].plot(kind='line', figsize=(8, 4), title='T1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['L1'].plot(kind='line', figsize=(8, 4), title='L1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17['H1'].plot(kind='line', figsize=(8, 4), title='H1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_18['S1'].plot(kind='line', figsize=(8, 4), title='S1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['KV'].value_counts()
    for x_label, grp in _df_19.groupby('GT')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('GT')
_ = plt.ylabel('KV')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['KT'].value_counts()
    for x_label, grp in _df_20.groupby('KV')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('KV')
_ = plt.ylabel('KT')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_21['GT'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_21, x='T1', y='GT', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_22['KV'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_22, x='T1', y='KV', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_23['KT'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_23, x='T1', y='KT', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_24['GT'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_24, x='L1', y='GT', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# 4. Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu thì điền giá trị 0
df["DT"].fillna(0, inplace=True)
df.head(10)

/tmp/ipython-input-1521303477.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["DT"].fillna(0, inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,0.0,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,0.0,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,0.0,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,0.0,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,0.0,1,4.00,4.75,5.50,D1

In [ ]:
# 5. Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử dụng phương pháp Mean
df['T1'].fillna(df['T1'].mean(), inplace=True)
df.head(10)

/tmp/ipython-input-978402170.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['T1'].fillna(df['T1'].mean(), inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,0.0,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,0.0,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,0.0,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,0.0,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,0.0,1,4.00,4.75,5.50,D1

In [ ]:
# 6. Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại
score_cols = [col for col in df.columns if col[0] in ['T','L','H','S','V','X','D','N','D']]

df[score_cols] = df[score_cols].apply(lambda x: x.fillna(x.mean()))
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [ ]:
# 7. Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và 12.
# Công thức tính: TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10
# Lớp 10
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] +
              df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10

# Lớp 11
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] +
              df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10

# Lớp 12
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] +
              df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,GT,DT,KV,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,F,0.0,2NT,3.25,3.25,4.50,A1,7.00,7.54,7.01
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,M,0.0,1,6.00,4.00,3.50,C,4.69,5.47,5.07
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,M,0.0,1,5.00,6.75,4.00,C,5.77,5.38,6.04
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,M,0.0,1,4.25,4.25,5.25,D1,6.21,5.20,6.88
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,M,0.0,2NT,4.25,4.50,5.00,A,6.50,6.36,6.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,F,0.0,1,5.25,1.50,6.25,C,7.43,7.42,6.83
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,F,0.0,1,5.25,3.75,4.75,C,4.93,5.15,6.39
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,M,0.0,2NT,7.00,8.00,4.00,C,7.05,7.84,7.67
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,M,0.0,1,5.00,3.50,5.50,C,4.15,4.72,5.29
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,M,0.0,2NT,5.25,2.50,4.25,C,5.26,5.72,5.85

In [ ]:
# 8. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp 10, 11, 12 như sau:
# Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)
# Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)
# Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)
# Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)
# Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)
def xep_loai(tbm):
    if tbm < 5.0:
        return 'Y'
    elif tbm < 6.5:
        return 'TB'
    elif tbm < 8.0:
        return 'K'
    elif tbm < 9.0:
        return 'G'
    else:
        return 'XS'

df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,3.25,3.25,4.50,A1,7.00,7.54,7.01,K,K,K
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.00,4.00,3.50,C,4.69,5.47,5.07,Y,TB,TB
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.00,6.75,4.00,C,5.77,5.38,6.04,TB,TB,TB
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,4.25,4.25,5.25,D1,6.21,5.20,6.88,TB,TB,K
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,4.25,4.50,5.00,A,6.50,6.36,6.99,K,TB,K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,5.25,1.50,6.25,C,7.43,7.42,6.83,K,K,K
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,5.25,3.75,4.75,C,4.93,5.15,6.39,Y,TB,TB
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.00,8.00,4.00,C,7.05,7.84,7.67,K,K,K
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,5.00,3.50,5.50,C,4.15,4.72,5.29,Y,Y,TB
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.25,2.50,4.25,C,5.26,5.72,5.85,TB,TB,TB

In [ ]:
# 9. Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương pháp Min-Max Normalization
def min_max_to_4(x):
    return (x - x.min()) / (x.max() - x.min()) * 4

df['US_TBM1'] = min_max_to_4(df['TBM1'])
df['US_TBM2'] = min_max_to_4(df['TBM2'])
df['US_TBM3'] = min_max_to_4(df['TBM3'])
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,A1,7.00,7.54,7.01,K,K,K,2.930693,3.029126,2.537143
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,C,4.69,5.47,5.07,Y,TB,TB,0.643564,1.019417,0.320000
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,C,5.77,5.38,6.04,TB,TB,TB,1.712871,0.932039,1.428571
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,D1,6.21,5.20,6.88,TB,TB,K,2.148515,0.757282,2.388571
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,A,6.50,6.36,6.99,K,TB,K,2.435644,1.883495,2.514286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,C,7.43,7.42,6.83,K,K,K,3.356436,2.912621,2.331429
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,C,4.93,5.15,6.39,Y,TB,TB,0.881188,0.708738,1.828571
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,C,7.05,7.84,7.67,K,K,K,2.980198,3.320388,3.291429
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,C,4.15,4.72,5.29,Y,Y,TB,0.108911,0.291262,0.571429
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,C,5.26,5.72,5.85,TB,TB,TB,1.207921,1.262136,1.211429

In [ ]:
# 10. Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau
# Với khối A, A1 nếu [(DH1*2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
# Với khối B nếu [(DH1 + DH2*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
# Với khối khác nếu [(DH1+ DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
def ket_qua_xt(row):
    if row['KT'] in ['A', 'A1']:
        score = (row['DH1']*2 + row['DH2'] + row['DH3']) / 4
    elif row['KT'] == 'B':
        score = (row['DH1'] + row['DH2']*2 + row['DH3']) / 4
    else:
        score = (row['DH1'] + row['DH2'] + row['DH3']) / 3

    return 1 if score >= 5.0 else 0

df['KQXT'] = df.apply(ket_qua_xt, axis=1)
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.930693,3.029126,2.537143,0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,0.643564,1.019417,0.320000,0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,1.712871,0.932039,1.428571,1
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.148515,0.757282,2.388571,0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.435644,1.883495,2.514286,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,3.356436,2.912621,2.331429,0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,0.881188,0.708738,1.828571,0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.980198,3.320388,3.291429,1
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,0.108911,0.291262,0.571429,0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,1.207921,1.262136,1.211429,0

In [ ]:
# 11. Lưu trữ dữ liệu xuống ổ đĩa thành file processed_dulieuxettuyendaihoc.csv
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.930693,3.029126,2.537143,0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,0.643564,1.019417,0.320000,0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,1.712871,0.932039,1.428571,1
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.148515,0.757282,2.388571,0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.435644,1.883495,2.514286,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,3.356436,2.912621,2.331429,0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,0.881188,0.708738,1.828571,0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.980198,3.320388,3.291429,1
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,0.108911,0.291262,0.571429,0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,1.207921,1.262136,1.211429,0